openeuropa/oe_link_lists

docker-compose.yml, oe_link_lists.services.yml, phpunit.xml.dist, runner.yml.dist, src/Annotation/LinkSource.php, src/ExternalLinkSourcePluginInterface.php, src/LinkSourceInterface.php, src/LinkSourcePluginBase.php, src/LinkSourcePluginManager.php, src/LinkSourcePluginManagerInterface.php, src/Plugin/ExternalLinkSourcePluginBase.php, tests/FunctionalJavascript/SourcePluginConfigTest.php, tests/modules/oe_link_lists_test/oe_link_lists_test.info.yml, tests/modules/oe_link_lists_test/oe_link_lists_test.module, tests/modules/oe_link_lists_test/src/Plugin/LinkSource/Bar.php, tests/modules/oe_link_lists_test/src/Plugin/LinkSource/Foo.php
This PR contains the plugin type and base classes but also a very comprehensive example on how these plugins can be integrated with forms and deal with their own configuration within this context.
=> OPENEUROPA-2296: Create LinkSource plugin type and base classes

docker-compose.yml, oe_link_lists.info.yml, oe_link_lists.permissions.yml, src/Entity/LinkListLink.php, src/Entity/LinkListLinkInterface.php, src/Form/LinkListLinkForm.php, src/Plugin/Validation/Constraint/LinkListLinkFieldsRequiredValidator.php, tests/FunctionalJavascript/LinkListLinkFormTest.php, tests/Kernel/LinkListLinkTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2294: Add conditional fields.

modules/oe_link_lists_internal_source/tests/src/Kernel/InternalLinkSourcePluginTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2597: Add missed test coverage.

src/Plugin/Field/FieldWidget/LinkListConfigurationWidget.php, tests/FunctionalJavascript/LinkListDisplayConfigurationFormTest.php
Currently invalid URLs like invalid://not-a-valid-protocol can be added.
These constraints are implemented the link module.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OPENEUROPA-2507: [oe_link_lists] Add extra validation for the "See all" target field.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Update changelog for release 0.5.0.

modules/oe_link_lists_aggregator_item_access/oe_link_lists_aggregator_item_access.module, modules/oe_link_lists_manual_source/oe_link_lists_manual_source.module, modules/oe_link_lists_manual_source/src/Entity/LinkListLink.php, modules/oe_link_lists_manual_source/src/EventSubscriber/DefaultManualLinksResolverSubscriber.php, modules/oe_link_lists_manual_source/src/LinkListLinkInlineForm.php, modules/oe_link_lists_manual_source/tests/FunctionalJavascript/ManualLinkListFormTest.php, modules/oe_link_lists_manual_source/tests/Kernel/ManualLinkSourcePluginTest.php, modules/oe_link_lists_manual_source/tests/modules/oe_link_lists_manual_source_test/config/install/core.entity_form_display.link_list_link.internal_route.default.yml, modules/oe_link_lists_manual_source/tests/modules/oe_link_lists_manual_source_test/config/install/field.field.link_list_link.internal_route.url.yml, modules/oe_link_lists_manual_source/tests/modules/oe_link_lists_manual_source_test/config/install/oe_link_lists_manual_source.link_list_link_type.internal_route.yml, modules/oe_link_lists_manual_source/tests/modules/oe_link_lists_manual_source_test/oe_link_lists_manual_source_test.info.yml, modules/oe_link_lists_manual_source/tests/modules/oe_link_lists_manual_source_test/oe_link_lists_manual_source_test.install
Removes hardcoded assumptions to only two link list link bundles.
=> OPENEUROPA-0000: Opening to other manual link bundles.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-0000: Preparing for release 0.10.0.

src/LinkListViewBuilder.php, tests/src/FunctionalJavascript/LinkListConfigurationFormTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-1116: Prevent a crash if the "more" link entity is deleted.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-0000: Prepare 0.13.0 release.

composer.json
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-2035: Revert fixing xdebug-handler version.

CHANGELOG.md
Prepare release 0.14.0.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 0.14.0.

oe_link_lists.post_update.php, src/Plugin/Field/FieldWidget/LinkListConfigurationWidget.php, tests/src/FunctionalJavascript/LinkListConfigurationFormTest.php
The first commit proves the bug.
=> EWPP-2056: More link plugin config form fix to not disappear on other AJAX rebuilds.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 0.15.0.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 0.15.1.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 0.16.0.

modules/oe_link_lists_rss_source/tests/modules/oe_link_lists_rss_source_test/oe_link_lists_rss_source_test.module
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-0000: Fix test modulo hook name.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 0.17.0.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 0.17.1.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 0.17.2.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 0.18.0

src/EventSubscriber/DefaultEntityValueResolverSubscriber.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-2919: Fix issue with empty link_list teaser.

modules/oe_link_lists_rss_source/src/Plugin/LinkSource/RssLinksSource.php, modules/oe_link_lists_rss_source/tests/src/FunctionalJavascript/RssLinksTranslationTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-3529: Prevent duplication of aggregator feed items even if we have several feeds for same URL.

CHANGELOG.md
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> Prepare release 1.1.1.

.drone.yml, src/LinkListViewBuilder.php
…guration.
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-4307: Pass original internal link list id to source plugin configuration.

.drone.yml, modules/oe_link_lists_local/tests/src/Functional/LocalLinkListsTest.php, phpunit.xml.dist
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> OEL-3032: Update to Drupal 10.3

modules/oe_link_lists_manual_source/src/EventSubscriber/DefaultManualLinksResolverSubscriber.php, modules/oe_link_lists_manual_source/tests/src/FunctionalJavascript/ManualLinkListFormTest.php
- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:
```sh
```
=> EWPP-5664: Harmonise rendering of manual external links.
